server: # 应用基础配置
  listen: 0.0.0.0
  port: 12888

log:
  level: info                 # 日志等级
  root_dir: ./log/         # 日志根目录
  filename: monaPanel.log           # 日志文件名称
  format:                     # 写入格式 可选json
  show_line: true             # 是否显示调用行
  max_backups: 3              # 旧文件的最大个数
  max_size: 64               # 日志文件最大大小（MB）
  max_age: 28                 # 旧文件的最大保留天数
  compress: true              # 是否压缩